---
- name: create a cron job
  hosts: all
  tasks:

    - name: schedule cron
      cron: 
        name: this job is schedule by ansible
        minute: "0"
        hour: "10"
        day: "*"
        month: "*"
        weekday: "4"
        user: root
        job: /root/cfile.sh

